name: Publish in DockerHub

on:  
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Extract maven version
        run: echo ::set-output name=tag::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
        id: project
      - name: Get date
        run: echo ::set-output name=value::$(date +'%Y%m%d.%H%M%S')
        id: timestamp
# This is the most complex way of doing it. But it works
# To use this form call it with ${{steps.exercice.outputs.version}}
      - name: Tag of exercice 1
        run: echo ::set-output name=version::$(A=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) ; B=$(date +'%Y%m%d.%H%M%S') ; echo $A"-"$B)
        id: exercice
      - name: Run tests
        run: mvn test
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/items:${{steps.project.outputs.tag}}-${{steps.timestamp.outputs.value}}
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:${{steps.project.outputs.tag}}-${{steps.timestamp.outputs.value}}
